--CREATE PRODUCTS TABLES

CREATE SEQUENCE PRODUCTS_SEQ;

CREATE TABLE PRODUCT_VEHICLE{
  ID INTEGER NOT NULL DEFAULT NEXTVAL('PRODUCTS_SEQ'),
  PRICE NUMERIC(10, 4) NOT NULL,
  COLORS VARCHAR(100) NOT NULL,
  SOUND_TYPE VARCHAR(15) NOT NULL,
  CONSTRAINT PV_PK PRIMARY KEY(ID)
}

CREATE TABLE PRODUCT_BEER{
  ID INTEGER NOT NULL DEFAULT NEXTVAL('PRODUCTS_SEQ'),
  PRICE NUMERIC(10, 4) NOT NULL,

  COLORS VARCHAR(100) NOT NULL,
  SOUND_TYPE VARCHAR(15) NOT NULL,
  CONSTRAINT PV_PK PRIMARY KEY(ID)
}